name: Build with Gradle

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

env:
  JAVA_VERSION: '22'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  build:
    name: Build and test application
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build and Test
        run: ./gradlew test